language: objective-c
xcode_workspace: RPerformanceTracking.xcworkspace
xcode_scheme: Tests
osx_image: xcode9.1

before_install:
- gem uninstall --force -x -i /Users/travis/.rvm/gems/ruby-2.4.2@global xcodeproj
- gem install -q -N -f --no-update-sources xcodeproj:1.5.7
- gem update fastlane --no-ri --no-rdoc --no-document
- pod repo update

script: fastlane ci

after_success:
- bash <(curl -s https://codecov.io/bash) -f ./artifacts/coverage/cobertura.xml -X coveragepy -X gcov -X xcode
